version: 2
jobs:
  build:
    docker:
      - image: node:6
    steps:
      - checkout
      - run: touch myfile
      - run: sleep 5
  test:
    docker:
      - image: node:6
    steps:
      - checkout
      - run: ls
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
